[2022-01-13 14:55:35,326] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: sample-dag-1.task_1 manual__2022-01-13T09:25:24.881959+00:00 [queued]>
[2022-01-13 14:55:35,341] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: sample-dag-1.task_1 manual__2022-01-13T09:25:24.881959+00:00 [queued]>
[2022-01-13 14:55:35,341] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-13 14:55:35,341] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-13 14:55:35,341] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-13 14:55:35,356] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): task_1> on 2022-01-13 09:25:24.881959+00:00
[2022-01-13 14:55:35,360] {standard_task_runner.py:52} INFO - Started process 55550 to run task
[2022-01-13 14:55:35,370] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'sample-dag-1', 'task_1', 'manual__2022-01-13T09:25:24.881959+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/wf1.py', '--cfg-path', '/var/folders/9x/87f7qfrd51l90dl7bb9hvr_w0000gq/T/tmpgmmxlt4_', '--error-file', '/var/folders/9x/87f7qfrd51l90dl7bb9hvr_w0000gq/T/tmpogl_sr9o']
[2022-01-13 14:55:35,374] {standard_task_runner.py:77} INFO - Job 20: Subtask task_1
[2022-01-13 14:55:35,476] {logging_mixin.py:109} INFO - Running <TaskInstance: sample-dag-1.task_1 manual__2022-01-13T09:25:24.881959+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-01-13 14:55:35,562] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=sample-dag-1
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2022-01-13T09:25:24.881959+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-13T09:25:24.881959+00:00
[2022-01-13 14:55:35,684] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/varunjain/Server/Workflow/airflow/dags/wf1.py", line 21, in _task_1
    return result.get()
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/celery/result.py", line 224, in get
    return self.backend.wait_for_pending(
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/celery/backends/base.py", line 756, in wait_for_pending
    meta = self.wait_for(
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/celery/backends/base.py", line 1087, in _is_disabled
    raise NotImplementedError(E_NO_BACKEND.strip())
NotImplementedError: No result backend is configured.
Please see the documentation for more information.
[2022-01-13 14:55:35,710] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=sample-dag-1, task_id=task_1, execution_date=20220113T092524, start_date=20220113T092535, end_date=20220113T092535
[2022-01-13 14:55:35,728] {standard_task_runner.py:89} ERROR - Failed to execute job 20 for task task_1
Traceback (most recent call last):
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/varunjain/Server/Workflow/airflow/dags/wf1.py", line 21, in _task_1
    return result.get()
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/celery/result.py", line 224, in get
    return self.backend.wait_for_pending(
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/celery/backends/base.py", line 756, in wait_for_pending
    meta = self.wait_for(
  File "/Users/varunjain/.virtualenvs/airflow-poc/lib/python3.8/site-packages/celery/backends/base.py", line 1087, in _is_disabled
    raise NotImplementedError(E_NO_BACKEND.strip())
NotImplementedError: No result backend is configured.
Please see the documentation for more information.
[2022-01-13 14:55:35,761] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-13 14:55:35,829] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
